version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:12.9.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: type-check:client
          command: yarn type-check:client
      - run:
          name: type-check:server
          command: yarn type-check:server
      - run:
          name: stylelint
          command: yarn stylelint
      - run:
          name: Lint
          command: yarn lint
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
  build-deploy:
    docker:
      - image: circleci/node:12.9.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Set up GitHub user name
          command: git config user.name $GITHUB_NAME
      - run:
          name: Set up GitHub user email
          command: git config user.email $GITHUB_EMAIL
      - run:
          name: Deploy
          command: yarn deploy
workflows:
  version: 2
  deploy:
    jobs:
      - lint
      - build-deploy:
          requires:
            - lint
          filters:
            branches:
              only: master
