version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1
    working_directory: ~/repo
    branches:
      ignore:
        - gh-pages
    steps:
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: typecheck
          command: yarn type-check
      - run:
          name: stylelint
          command: yarn stylelint
      - run:
          name: Lint
          command: yarn lint
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
