version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1
    working_directory: ~/repo
    steps:
      - run: yarn install
      - run: yarn type-check
      - run: yarn stylelint
      - run: yarn lint
